//#ENJOY BRO😍
const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "Kermd237@gmail.com";
global.location = "Douala, Cameroun";
global.mongodb = process.env.MONGODB_URL || "mongodb+srv://Rayan:<Emmanuel237>@cluster0.8twd0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";
global.allowJids = process.env.ALLOW_JID || "null";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Africa/Douala";
global.github = process.env.GITHUB || "https://github.com/Kgtech-cmr/KERM_MD-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029VailVtqE50UiB1PLBL1T";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029VailVtqE50UiB1PLBL1T";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/40ffc2a288542560c887c.jpg";
global.devs = "94767015325";
global.sudo = process.env.SUDO || "94767015325";
global.owner = process.env.OWNER_NUMBER || "94767015325";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "false";
global.userImages = process.env.USER_IMAGES || "https://files.catbox.moe/kbc224.mp4,https://files.catbox.moe/dhii42.mp4,https://files.catbox.moe/lgj91g.mp4,https://files.catbox.moe/hvjoe6.mp4,https://files.catbox.moe/4ogeum.mp4,https://files.catbox.moe/0cmaxl.jpg";
global.waPresence = process.env.WAPRESENCE || "available";
global.readcmds = process.env.READ_COMMAND || "true";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "false";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://kerm-session-2c65.onrender.com";

global.SESSION_ID =
  process.env.SESSION_ID ||
  "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUdwZ1pQbGlYcHNKQnlFemd6MmJiQmZPSUFxYzRVbGxxTUY3NjFkTTUzQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRXRKclJHb2RreHFPNlJUeG1oRHg5TWVpNFpBRG5QWnZCY3pTV2hsb2dqZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvREpvMmZYRVdYTmpzWWlUZThFOGVZVkNZdGwxVzdBNFJ6RzlLR1JJWkdNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2dXZXNXNRM3AwQnpWck5qTnJMWTZXLzJSVWtFVHhwNFF1dVovQ3Y0dWs0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVOZHlZR3NRWVoxTWVSZCtCbmZCajZSU2pTS0NmQW5zanZBZWlnSDJnWFE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdiVTY1SkhXTTZySVhTUm5EOEhkeUtvWHFCTUpiVnczOTlKWkwyaHROUVk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUNuTTRBUVBlWHNtaENRQ2xRanJQQk0rL21qRWlIOTdGR21rT004ejQwaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidDF6bjFmcDRpVUVTMklqVnd4OEoxOVBEV281cGNmV2tpT3hSb0I2bThRaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InIwWDFuRDh0L21YdG45T252OSthY2RjbHVNTkpxME1laGNCMWd0L3p2S3FNWEZLVWJyakFyWkEyQU00TWtYY29YeGI2NThWY21nbDVWVnNSdzNCU2hRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjgsImFkdlNlY3JldEtleSI6IlQ2RVljWGJjT3JXM0Q1Yk80VXFQY2dNbUI2S1lQaWU1dUtVRGlRWWdnbW89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRTNCQUYwRDQxNkQ5MTZCOTIyQjUzRjQxMjQyRThCNUIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2NH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQjI2MENGNUFFQUI0MjBFMTE1NTAxMzYyNUQ0QTlGQUEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2NH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMjg4M0UzRUY0OEU2NzY0NzBDRkM2RkRBMEJBMjAyNjgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2N30seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzgwOEE0OURCRDNCQkQ5RDE0NzkxNjk1NDM1MUIzQ0MifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2N31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiTzRaS2tVT3VSRjY3bXh1WnY4QU1xUSIsInBob25lSWQiOiJjMTc4NDdiMC04YWNjLTRmMWUtYjllNS1kYzliNWU1MDc0YTMiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0wzbTZBRlhNOE1YWC80S0FkQS9PMXFBREZZPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6NExRSFVOUkZhRlFhNGI3ZUM3dG1ZbnF6Tlk9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNOU0Q3ZU1HRU1LRWk3Z0dHQVVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJYZ0pIaDkwZWtuS0R4dERVRmZReFBjN0xkM3M0S0ZZSVpmNEM4MWhGZ1M0PSIsImFjY291bnRTaWduYXR1cmUiOiJyRitURkYzMXluOXBNMzBKRzhHVTVOMCtSdS9KVFhuQkdZOG94bVJQY1prSXR2YTlDZlB4VWRXTGJnM1VQeGhSVUpPMDVXWHFjUE5xTWVUV0IrNDNBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoidkdlM24rVTh5K1ArZ2hoTXJOc2RSWGltOXgwR1U1ZjhBVXZucnN1UEM2ZXpuRi84QWpFZHR6WGpSVnpWUFp2NkxiUnhtMmZPRGRUd0FNY0hVUWY0aWc9PSJ9LCJtZSI6eyJpZCI6Ijk0NzY3MDE1MzI1OjI5QHMud2hhdHNhcHAubmV0IiwibGlkIjoiNDYwODU1NTI3MzQ0NDY6MjlAbGlkIiwibmFtZSI6IkthdmVlbiJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NzAxNTMyNToyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWNENSNGZkSHBKeWc4YlExQlgwTVQzT3kzZDdPQ2hXQ0dYK0F2TllSWUV1In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgyMzQwNjMsImxhc3RQcm9wSGFzaCI6IjI4WlJsYSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT1dlIn0=Gl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiTzRaS2tVT3VSRjY3bXh1WnY4QU1xUSIsInBob25lSWQiOiJjMTc4NDdiMC04YWNjLTRmMWUtYjllNS1kYzliNWU1MDc0YTMiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0wzbTZBRlhNOE1YWC80S0FkQS9PMXFBREZZPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6NExRSFVOUkZhRlFhNGI3ZUM3dG1ZbnF6Tlk9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNOU0Q3ZU1HRU1LRWk3Z0dHQVVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJYZ0pIaDkwZWtuS0R4dERVRmZReFBjN0xkM3M0S0ZZSVpmNEM4MWhGZ1M0PSIsImFjY291bnRTaWduYXR1cmUiOiJyRitURkYzMXluOXBNMzBKRzhHVTVOMCtSdS9KVFhuQkdZOG94bVJQY1prSXR2YTlDZlB4VWRXTGJnM1VQeGhSVUpPMDVXWHFjUE5xTWVUV0IrNDNBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoidkdlM24rVTh5K1ArZ2hoTXJOc2RSWGltOXgwR1U1ZjhBVXZucnN1UEM2ZXpuRi84QWpFZHR6WGpSVnpWUFp2NkxiUnhtMmZPRGRUd0FNY0hVUWY0aWc9PSJ9LCJtZSI6eyJpZCI6Ijk0NzY3MDE1MzI1OjI5QHMud2hhdHNhcHAubmV0IiwibGlkIjoiNDYwODU1NTI3MzQ0NDY6MjlAbGlkIiwibmFtZSI6IkthdmVlbiJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NzAxNTMyNToyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWNENSNGZkSHBKeWc4YlExQlgwTVQzT3kzZDdPQ2hXQ0dYK0F2TllSWUV1In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgyMzQwNjMsImxhc3RQcm9wSGFzaCI6IjI4WlJsYSIsIm15QXBwU3RhdGVLZXlJZCI6eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUdwZ1pQbGlYcHNKQnlFemd6MmJiQmZPSUFxYzRVbGxxTUY3NjFkTTUzQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRXRKclJHb2RreHFPNlJUeG1oRHg5TWVpNFpBRG5QWnZCY3pTV2hsb2dqZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvREpvMmZYRVdYTmpzWWlUZThFOGVZVkNZdGwxVzdBNFJ6RzlLR1JJWkdNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2dXZXNXNRM3AwQnpWck5qTnJMWTZXLzJSVWtFVHhwNFF1dVovQ3Y0dWs0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVOZHlZR3NRWVoxTWVSZCtCbmZCajZSU2pTS0NmQW5zanZBZWlnSDJnWFE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdiVTY1SkhXTTZySVhTUm5EOEhkeUtvWHFCTUpiVnczOTlKWkwyaHROUVk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUNuTTRBUVBlWHNtaENRQ2xRanJQQk0rL21qRWlIOTdGR21rT004ejQwaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidDF6bjFmcDRpVUVTMklqVnd4OEoxOVBEV281cGNmV2tpT3hSb0I2bThRaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InIwWDFuRDh0L21YdG45T252OSthY2RjbHVNTkpxME1laGNCMWd0L3p2S3FNWEZLVWJyakFyWkEyQU00TWtYY29YeGI2NThWY21nbDVWVnNSdzNCU2hRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjgsImFkdlNlY3JldEtleSI6IlQ2RVljWGJjT3JXM0Q1Yk80VXFQY2dNbUI2S1lQaWU1dUtVRGlRWWdnbW89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRTNCQUYwRDQxNkQ5MTZCOTIyQjUzRjQxMjQyRThCNUIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2NH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQjI2MENGNUFFQUI0MjBFMTE1NTAxMzYyNUQ0QTlGQUEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2NH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMjg4M0UzRUY0OEU2NzY0NzBDRkM2RkRBMEJBMjAyNjgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2N30seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NjcwMTUzMjVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzgwOEE0OURCRDNCQkQ5RDE0NzkxNjk1NDM1MUIzQ0MifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzNDA2N31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiTzRaS2tVT3VSRjY3bXh1WnY4QU1xUSIsInBob25lSWQiOiJjMTc4NDdiMC04YWNjLTRmMWUtYjllNS1kYzliNWU1MDc0YTMiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0wzbTZBRlhNOE1YWC80S0FkQS9PMXFBREZZPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6NExRSFVOUkZhRlFhNGI3ZUM3dG1ZbnF6Tlk9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNOU0Q3ZU1HRU1LRWk3Z0dHQVVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJYZ0pIaDkwZWtuS0R4dERVRmZReFBjN0xkM3M0S0ZZSVpmNEM4MWhGZ1M0PSIsImFjY291bnRTaWduYXR1cmUiOiJyRitURkYzMXluOXBNMzBKRzhHVTVOMCtSdS9KVFhuQkdZOG94bVJQY1prSXR2YTlDZlB4VWRXTGJnM1VQeGhSVUpPMDVXWHFjUE5xTWVUV0IrNDNBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoidkdlM24rVTh5K1ArZ2hoTXJOc2RSWGltOXgwR1U1ZjhBVXZucnN1UEM2ZXpuRi84QWpFZHR6WGpSVnpWUFp2NkxiUnhtMmZPRGRUd0FNY0hVUWY0aWc9PSJ9LCJtZSI6eyJpZCI6Ijk0NzY3MDE1MzI1OjI5QHMud2hhdHNhcHAubmV0IiwibGlkIjoiNDYwODU1NTI3MzQ0NDY6MjlAbGlkIiwibmFtZSI6IkthdmVlbiJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NzAxNTMyNToyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWNENSNGZkSHBKeWc4YlExQlgwTVQzT3kzZDdPQ2hXQ0dYK0F2TllSWUV1In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgyMzQwNjMsImxhc3RQcm9wSGFzaCI6IjI4WlJsYSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT1dlIn0IkFBQUFBT1dlIn0="
module.exports = {
  menu: process.env.MENU || "1",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "`BRAND PRODUCT OF ☞⌜ KG TECH⌝☜`",
  author: process.env.PACK_AUTHER || "KG TECH",
  packname: process.env.PACK_NAME || "Kerm-MD-V2",
  botname: process.env.BOT_NAME || "ᵏᵍ┘𝙺𝙴𝚁𝙼_𝙼𝙳_𝚅𝟸𖤐",
  ownername: process.env.OWNER_NAME || "☞⌜ KG TECH⌝☜",
  errorChat: process.env.ERROR_CHAT || "",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "tCxobE1FqJgfbDZgsYQNHBFB",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "...d336",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  LANG: (process.env.THEME || "KERM").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
